### ISSUE TITLE
Todos separation

### ISSUE THREAD

**Issue by markosole** [appwrite/todo-with-vue#42]
I would like to report issue with user's todo's separation. I've deployed app on my localhost, creaded DB and collection. Registered two users and logged them in. Both users are sharing one Todo list and they do not have their own. 

Not sure if this is a bug or feature :) I would expect separation in Todos per user.

I am using latest version of Appwrite.

**Comment by stnguyen90** [comment]
@markosole, thanks for creating this issue! 🙏🏼 It looks like the README is a little outdated. Instead of granting all users full CRUD access on the collection, it should just be "create" access, and document security should be enabled. This will allow users to create todos, but each todo will default to only being accessible by the user who created it.

**Comment by markosole** [comment]
Hi @stnguyen90  fantastic, thanks for reply. Well we are here to help and support open source aren't we :). 
Latest AppWrite looks a bit different too, nothing major really but would be helpfull for those who are just starting.

Just tested what you suggested and works perfectly. I am quiet new to VUE and AppWrite and I am looking into this "login" flash when you refresh the page while you'r already logged in. It's jut for fraction of a second until Login status is checked I guess.
